blank_issues_enabled: false
contact_links:
  - name: Security Issues
    url: https://github.com/KenkoGeek/mcp-gh-code-review/security/advisories/new
    about: Please report security vulnerabilities privately
  - name: Discussions
    url: https://github.com/KenkoGeek/mcp-gh-code-review/discussions
    about: Ask questions and discuss ideas with the community